export const friendlyNames: Record<string, string> = {
  get_accounts: "Checking accounts",
  get_transactions: "Looking up transactions",
  get_spending_summary: "Analyzing spending",
  get_income_summary: "Analyzing income",
  get_budget_status: "Checking budgets",
  get_goals: "Checking goals",
  get_net_worth: "Calculating net worth",
  get_cash_flow: "Analyzing cash flow",
  get_categories: "Getting categories",
  create_account: "Creating account",
  update_account: "Updating account",
  create_transaction: "Recording transaction",
  update_transaction: "Updating transaction",
  delete_transaction: "Deleting transaction",
  create_budget: "Creating budget",
  update_budget: "Updating budget",
  create_goal: "Creating goal",
  update_goal: "Updating goal",
  fund_goal: "Funding goal",
  withdraw_from_goal: "Withdrawing from goal",
  save_memory: "Saving to memory",
  update_memory: "Updating memory",
  delete_memory: "Removing memory",
  list_memories: "Listing memories",
};

export const completedNames: Record<string, string> = {
  get_accounts: "Checked accounts",
  get_transactions: "Looked up transactions",
  get_spending_summary: "Analyzed spending",
  get_income_summary: "Analyzed income",
  get_budget_status: "Checked budgets",
  get_goals: "Checked goals",
  get_net_worth: "Calculated net worth",
  get_cash_flow: "Analyzed cash flow",
  get_categories: "Got categories",
  create_account: "Account created",
  update_account: "Account updated",
  create_transaction: "Transaction recorded",
  update_transaction: "Transaction updated",
  delete_transaction: "Transaction deleted",
  create_budget: "Budget created",
  update_budget: "Budget updated",
  create_goal: "Goal created",
  update_goal: "Goal updated",
  fund_goal: "Funded goal",
  withdraw_from_goal: "Withdrew from goal",
  save_memory: "Saved to memory",
  update_memory: "Memory updated",
  delete_memory: "Memory removed",
  list_memories: "Listed memories",
};
