export const friendlyNames: Record<string, string> = {
  get_accounts: "Checking accounts",
  get_transactions: "Looking up transactions",
  get_spending_summary: "Analyzing spending",
  get_income_summary: "Analyzing income",
  get_budget_status: "Checking budgets",
  get_goals: "Checking goals",
  get_net_worth: "Calculating net worth",
  get_cash_flow: "Analyzing cash flow",
  get_expense_categories: "Getting expense categories",
  get_income_sources: "Getting income sources",
  convert_currency: "Converting currency",
  create_asset_account: "Creating account",
  create_liability: "Creating credit/loan",
  update_account: "Updating account",
  create_expense_category: "Creating expense category",
  rename_expense_category: "Renaming expense category",
  delete_expense_category: "Deleting expense category",
  create_income_source: "Creating income source",
  rename_income_source: "Renaming income source",
  delete_income_source: "Deleting income source",
  record_expense: "Recording expense",
  record_income: "Recording income",
  record_transfer: "Recording transfer",
  update_transaction: "Updating transaction",
  delete_transaction: "Deleting transaction",
  create_budget: "Creating budget",
  update_budget: "Updating budget",
  create_goal: "Creating goal",
  update_goal: "Updating goal",
  fund_goal: "Funding goal",
  withdraw_from_goal: "Withdrawing from goal",
  batch_create_transactions: "Recording transactions",
  batch_delete_transactions: "Deleting transactions",
  batch_create_budgets: "Creating budgets",
  batch_fund_goals: "Funding goals",
  batch_create_goals: "Creating goals",
  batch_create_accounts: "Creating accounts",
  update_currency: "Updating currency",
  save_memory: "Saving to memory",
  update_memory: "Updating memory",
  delete_memory: "Removing memory",
  list_memories: "Listing memories",
};

export const completedNames: Record<string, string> = {
  get_accounts: "Checked accounts",
  get_transactions: "Looked up transactions",
  get_spending_summary: "Analyzed spending",
  get_income_summary: "Analyzed income",
  get_budget_status: "Checked budgets",
  get_goals: "Checked goals",
  get_net_worth: "Calculated net worth",
  get_cash_flow: "Analyzed cash flow",
  get_expense_categories: "Got expense categories",
  get_income_sources: "Got income sources",
  convert_currency: "Converted currency",
  create_asset_account: "Account created",
  create_liability: "Credit/loan created",
  update_account: "Account updated",
  create_expense_category: "Expense category created",
  rename_expense_category: "Expense category renamed",
  delete_expense_category: "Expense category deleted",
  create_income_source: "Income source created",
  rename_income_source: "Income source renamed",
  delete_income_source: "Income source deleted",
  record_expense: "Expense recorded",
  record_income: "Income recorded",
  record_transfer: "Transfer recorded",
  update_transaction: "Transaction updated",
  delete_transaction: "Transaction deleted",
  create_budget: "Budget created",
  update_budget: "Budget updated",
  create_goal: "Goal created",
  update_goal: "Goal updated",
  fund_goal: "Funded goal",
  withdraw_from_goal: "Withdrew from goal",
  batch_create_transactions: "Transactions recorded",
  batch_delete_transactions: "Transactions deleted",
  batch_create_budgets: "Budgets created",
  batch_fund_goals: "Goals funded",
  batch_create_goals: "Goals created",
  batch_create_accounts: "Accounts created",
  update_currency: "Currency updated",
  save_memory: "Saved to memory",
  update_memory: "Memory updated",
  delete_memory: "Memory removed",
  list_memories: "Listed memories",
};

export const failedNames: Record<string, string> = {
  get_accounts: "Failed to check accounts",
  get_transactions: "Failed to look up transactions",
  get_spending_summary: "Failed to analyze spending",
  get_income_summary: "Failed to analyze income",
  get_budget_status: "Failed to check budgets",
  get_goals: "Failed to check goals",
  get_net_worth: "Failed to calculate net worth",
  get_cash_flow: "Failed to analyze cash flow",
  get_expense_categories: "Failed to get expense categories",
  get_income_sources: "Failed to get income sources",
  convert_currency: "Failed to convert currency",
  create_asset_account: "Failed to create account",
  create_liability: "Failed to create credit/loan",
  update_account: "Failed to update account",
  create_expense_category: "Failed to create expense category",
  rename_expense_category: "Failed to rename expense category",
  delete_expense_category: "Failed to delete expense category",
  create_income_source: "Failed to create income source",
  rename_income_source: "Failed to rename income source",
  delete_income_source: "Failed to delete income source",
  record_expense: "Failed to record expense",
  record_income: "Failed to record income",
  record_transfer: "Failed to record transfer",
  update_transaction: "Failed to update transaction",
  delete_transaction: "Failed to delete transaction",
  create_budget: "Failed to create budget",
  update_budget: "Failed to update budget",
  create_goal: "Failed to create goal",
  update_goal: "Failed to update goal",
  fund_goal: "Failed to fund goal",
  withdraw_from_goal: "Failed to withdraw from goal",
  batch_create_transactions: "Failed to record transactions",
  batch_delete_transactions: "Failed to delete transactions",
  batch_create_budgets: "Failed to create budgets",
  batch_fund_goals: "Failed to fund goals",
  batch_create_goals: "Failed to create goals",
  batch_create_accounts: "Failed to create accounts",
  update_currency: "Failed to update currency",
  save_memory: "Failed to save memory",
  update_memory: "Failed to update memory",
  delete_memory: "Failed to remove memory",
  list_memories: "Failed to list memories",
};
